import type { Queryable } from '../db/client';
import type {
  AiActionKey,
  AiInterventionSummary,
  AlertCategory,
  AlertSeverity,
  CrowdLevel,
  TransitMode,
  VehicleStatus,
} from '../../shared/types';

/**
 * AI-decision repository — the database half of the interactive "AI Decision"
 * console. Nothing here invents numbers: the proposal is assembled from
 * `lines`, `line_stops`, `crowd_observations`, `vehicles` and `alerts`, and
 * applying a decision writes the ledger rows (`ai_decisions`,
 * `ai_decision_actions`), moves a real `vehicles` row into service and raises an
 * `alerts` event.
 *
 * DEMO / SIMULATED DATA: the underlying telemetry is generated by the demo seed.
 */

/* -------------------------------------------------------------------------- */
/* Reads                                                                      */
/* -------------------------------------------------------------------------- */

export interface LineContextRow {
  id: string;
  agency_id: string;
  agency_name: string;
  timezone: string;
  code: string;
  name: string;
  color: string;
  mode: TransitMode;
  capacity_per_vehicle: number;
  headway_minutes: number;
  /** Sum of daily boardings across the route's stops — the reach estimate. */
  corridor_daily_boardings: number;
}

export async function getLineContext(
  db: Queryable,
  lineIdOrCode: string,
): Promise<LineContextRow | null> {
  return db.one<LineContextRow>(
    `select
       l.id,
       l.agency_id,
       a.name        as agency_name,
       a.timezone,
       l.code,
       l.name,
       l.color,
       l.mode,
       l.capacity_per_vehicle,
       l.headway_minutes,
       (select coalesce(sum(s.daily_boardings), 0)::int
          from line_stops ls join stops s on s.id = ls.stop_id
         where ls.line_id = l.id) as corridor_daily_boardings
     from lines l
     join agencies a on a.id = l.agency_id
     where l.id = $1 or l.code = $1
     limit 1`,
    [lineIdOrCode],
  );
}

export interface ReserveVehicleRow {
  id: string;
  code: string;
  status: VehicleStatus;
  line_id: string;
  line_code: string;
  capacity_total: number;
  adherence_pct: number | string | null;
  last_ping: string | Date | null;
}

/**
 * Reserve units the engine may deploy: the line's own idle vehicles first, then
 * any idle vehicle in the network, then units held in maintenance.
 */
export async function listReserveVehicles(
  db: Queryable,
  lineId: string,
  limit = 5,
): Promise<ReserveVehicleRow[]> {
  return db.query<ReserveVehicleRow>(
    `select v.id, v.code, v.status, v.line_id, l.code as line_code,
            v.capacity_total, v.adherence_pct, v.last_ping
       from vehicles v
       join lines l on l.id = v.line_id
      where v.status in ('idle', 'maintenance')
      order by case when v.status = 'idle' then 0 else 1 end,
               case when v.line_id = $1 then 0 else 1 end,
               v.code
      limit $2`,
    [lineId, limit],
  );
}

export interface AlternativeLineRow {
  id: string;
  code: string;
  name: string;
  color: string;
  mode: TransitMode;
  headway_minutes: number;
  capacity_per_vehicle: number;
  shared_stops: number;
  shared_stop_name: string | null;
  /** Most recent measured load on the alternative corridor. */
  alt_ratio: number | string | null;
}

/**
 * The quietest route that shares at least one stop with this one — the corridor
 * the engine steers riders toward when a route is about to crowd.
 */
export async function findAlternativeLine(
  db: Queryable,
  lineId: string,
): Promise<AlternativeLineRow | null> {
  return db.one<AlternativeLineRow>(
    `with mine as (
       select stop_id from line_stops where line_id = $1
     ),
     alt as (
       select l.id, l.code, l.name, l.color, l.mode, l.headway_minutes,
              l.capacity_per_vehicle,
              count(distinct ls.stop_id)::int as shared_stops
         from line_stops ls
         join lines l on l.id = ls.line_id
        where ls.stop_id in (select stop_id from mine)
          and l.id <> $1
          and l.is_active
        group by l.id, l.code, l.name, l.color, l.mode, l.headway_minutes,
                 l.capacity_per_vehicle
     )
     select a.*, c.ratio as alt_ratio, c.stop_name as shared_stop_name
       from alt a
       left join lateral (
         select co.occupancy_ratio as ratio, s.name as stop_name
           from crowd_observations co
           join stops s on s.id = co.stop_id
          where co.line_id = a.id
            and co.stop_id in (select stop_id from mine)
          order by co.observed_at desc
          limit 1
       ) c on true
      order by coalesce(c.ratio, 0) asc, a.shared_stops desc
      limit 1`,
    [lineId],
  );
}

export interface PeakWindowRow {
  hour_of_day: number;
  p90_ratio: number | string;
  avg_ratio: number | string;
  day_offset: number;
  target_at: string | Date;
  /** `crossing` when the historical average crosses the threshold, else `peak`. */
  kind: 'crossing' | 'peak';
}

/**
 * The next recurring congestion window on a route's monitored stop, from the
 * 14-day hourly profile.
 *
 * Preference order: the earliest upcoming hour whose *average* load already
 * crosses the crowding threshold, otherwise the busiest upcoming hour (the next
 * peak window). Used when the engine scan finds no crossing in the next hours,
 * so the console reports the route's next risk instead of an empty panel.
 */
export async function findNextPeakWindow(
  db: Queryable,
  args: { lineId: string; stopId: string | null; thresholdRatio: number; timeZone: string },
): Promise<PeakWindowRow | null> {
  const localHour = await db.one<{ hour: number }>(
    `select extract(hour from (now() at time zone $1))::int as hour`,
    [args.timeZone],
  );
  const currentHour = Number(localHour?.hour ?? 0);

  const base = `with profile as (
       select hour_of_day,
              avg_ratio,
              p90_ratio,
              case when hour_of_day > $2 then 0 else 1 end as day_offset
         from v_line_hourly_profile
        where line_id = $1
          and ($3::text is null or stop_id = $3::text)
     )
     select p.hour_of_day, p.avg_ratio, p.p90_ratio, p.day_offset,
            ((date_trunc('day', now() at time zone $4)
              + make_interval(hours => p.hour_of_day)
              + make_interval(days => p.day_offset)) at time zone $4) as target_at
       from profile p`;
  const params = [args.lineId, currentHour, args.stopId, args.timeZone];

  const crossing = await db.one<PeakWindowRow>(
    `${base} where p.avg_ratio >= $5 order by p.day_offset, p.hour_of_day limit 1`,
    [...params, args.thresholdRatio],
  );
  if (crossing) return { ...crossing, kind: 'crossing' };

  const peak = await db.one<PeakWindowRow>(
    `${base} order by p.avg_ratio desc, p.day_offset, p.hour_of_day limit 1`,
    params,
  );
  return peak ? { ...peak, kind: 'peak' } : null;
}

export interface InterventionReadRow {
  id: string;
  line_id: string;
  route_number: string;
  route_name: string;
  color: string;
  mode: TransitMode;
  stop_id: string | null;
  stop_name: string | null;
  status: 'applied' | 'reverted';
  basis: 'live' | 'forecast' | 'profile';
  detected_at: string | Date;
  applied_at: string | Date | null;
  target_at: string | Date;
  minutes_to_congestion: number | null;
  current_pct: number | string;
  predicted_pct: number | string;
  projected_pct: number | string;
  relief_pct: number | string;
  confidence_pct: number | string;
  headcount: number;
  capacity: number;
  vehicles_in_service: number;
  vehicle_id: string | null;
  vehicle_code: string | null;
  alert_id: string | null;
  alert_title: string | null;
  applied_by: string | null;
  note: string | null;
  method: string;
  model_version: string;
  simulated: boolean;
  action_count: number;
  action_keys: AiActionKey[] | string;
}

const SELECT_INTERVENTION = `select * from v_ai_interventions`;

export async function listInterventions(
  db: Queryable,
  limit = 8,
): Promise<InterventionReadRow[]> {
  return db.query<InterventionReadRow>(
    `${SELECT_INTERVENTION}
      where status = 'applied'
      order by applied_at desc nulls last, detected_at desc
      limit $1`,
    [limit],
  );
}

/** Latest applied intervention per route — drives the "AI applied" route badge. */
export async function listInterventionsByLine(
  db: Queryable,
  windowHours = 24,
): Promise<InterventionReadRow[]> {
  return db.query<InterventionReadRow>(
    `select distinct on (line_id) *
       from v_ai_interventions
      where status = 'applied'
        and applied_at >= now() - make_interval(hours => $1)
      order by line_id, applied_at desc`,
    [windowHours],
  );
}

export async function countInterventionsSince(
  db: Queryable,
  windowHours = 24,
): Promise<number> {
  const row = await db.one<{ count: string }>(
    `select count(*)::text as count
       from ai_decisions
      where status = 'applied'
        and applied_at >= now() - make_interval(hours => $1)`,
    [windowHours],
  );
  return Number(row?.count ?? 0);
}

export async function getIntervention(
  db: Queryable,
  id: string,
): Promise<InterventionReadRow | null> {
  return db.one<InterventionReadRow>(`${SELECT_INTERVENTION} where id = $1`, [id]);
}

/** Applied interventions that must not be applied twice within the cooldown. */
export async function findRecentIntervention(
  db: Queryable,
  lineId: string,
  cooldownMinutes = 10,
): Promise<InterventionReadRow | null> {
  return db.one<InterventionReadRow>(
    `${SELECT_INTERVENTION}
      where line_id = $1 and status = 'applied'
        and applied_at >= now() - make_interval(mins => $2)
      order by applied_at desc
      limit 1`,
    [lineId, cooldownMinutes],
  );
}

/* -------------------------------------------------------------------------- */
/* Writes                                                                     */
/* -------------------------------------------------------------------------- */

export interface DecisionInsert {
  id: string;
  agencyId: string;
  lineId: string;
  stopId: string | null;
  basis: 'live' | 'forecast' | 'profile';
  detectedAt: Date;
  appliedAt: Date;
  targetAt: Date;
  horizonMinutes: number;
  minutesToCongestion: number | null;
  currentRatio: number;
  predictedRatio: number;
  projectedRatio: number;
  thresholdRatio: number;
  confidence: number;
  headcount: number;
  capacity: number;
  vehiclesInService: number;
  method: string;
  modelVersion: string;
  vehicleId: string | null;
  alertId: string | null;
  appliedBy: string;
  note: string;
}

export async function insertDecision(db: Queryable, input: DecisionInsert): Promise<void> {
  await db.query(
    `insert into ai_decisions
       (id, agency_id, line_id, stop_id, status, basis, detected_at, applied_at, target_at,
        horizon_minutes, minutes_to_congestion, current_ratio, predicted_ratio, projected_ratio,
        threshold_ratio, confidence, headcount, capacity, vehicles_in_service, method,
        model_version, vehicle_id, alert_id, applied_by, note, simulated)
     values ($1, $2, $3, $4, 'applied', $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
             $17, $18, $19, $20, $21, $22, $23, $24, true)`,
    [
      input.id,
      input.agencyId,
      input.lineId,
      input.stopId,
      input.basis,
      input.detectedAt,
      input.appliedAt,
      input.targetAt,
      input.horizonMinutes,
      input.minutesToCongestion,
      input.currentRatio,
      input.predictedRatio,
      input.projectedRatio,
      input.thresholdRatio,
      input.confidence,
      input.headcount,
      input.capacity,
      input.vehiclesInService,
      input.method,
      input.modelVersion,
      input.vehicleId,
      input.alertId,
      input.appliedBy,
      input.note,
    ],
  );
}

export interface DecisionActionInsert {
  seq: number;
  key: AiActionKey;
  title: string;
  detail: string;
  reliefFraction: number;
  expectedReliefPct: number;
  evidence: { label: string; value: string }[];
  targetLabel: string | null;
}

export async function insertDecisionActions(
  db: Queryable,
  decisionId: string,
  actions: DecisionActionInsert[],
  appliedAt: Date,
): Promise<void> {
  for (const action of actions) {
    await db.query(
      `insert into ai_decision_actions
         (decision_id, seq, action_key, title, detail, relief_fraction, expected_relief_pct,
          evidence, target_label, applied, applied_at)
       values ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9, true, $10)`,
      [
        decisionId,
        action.seq,
        action.key,
        action.title,
        action.detail,
        action.reliefFraction,
        action.expectedReliefPct,
        JSON.stringify(action.evidence),
        action.targetLabel,
        appliedAt,
      ],
    );
  }
}

/** Move a reserve unit onto the route — the "deploy additional vehicle" write. */
export async function assignVehicleToLine(
  db: Queryable,
  vehicleId: string,
  lineId: string,
  nextStopId: string | null,
): Promise<ReserveVehicleRow | null> {
  return db.one<ReserveVehicleRow>(
    `update vehicles
        set status = 'in_service',
            line_id = $2,
            next_stop_id = coalesce($3, next_stop_id),
            last_ping = now()
      where id = $1
      returning id, code, status, line_id,
                (select code from lines where id = vehicles.line_id) as line_code,
                capacity_total, adherence_pct, last_ping`,
    [vehicleId, lineId, nextStopId],
  );
}

/** Depot reserve: used when every listed vehicle is already committed. */
export async function createStandbyVehicle(
  db: Queryable,
  input: { id: string; code: string; lineId: string; nextStopId: string | null; capacity: number },
): Promise<ReserveVehicleRow | null> {
  return db.one<ReserveVehicleRow>(
    `insert into vehicles (id, line_id, code, capacity_seats, capacity_total, status,
                           next_stop_id, adherence_pct, last_ping)
     values ($1, $2, $3, $4, $5, 'in_service', $6, 100, now())
     returning id, code, status, line_id,
               (select code from lines where id = vehicles.line_id) as line_code,
               capacity_total, adherence_pct, last_ping`,
    [
      input.id,
      input.lineId,
      input.code,
      Math.round(input.capacity * 0.55),
      input.capacity,
      input.nextStopId,
    ],
  );
}

export interface InterventionAlertInsert {
  id: string;
  agencyId: string;
  lineId: string;
  stopId: string | null;
  severity: AlertSeverity;
  category: AlertCategory;
  title: string;
  body: string;
  endsAt: Date;
  issuedBy: string;
  reach: number;
}

export async function insertInterventionAlert(
  db: Queryable,
  input: InterventionAlertInsert,
): Promise<{ id: string } | null> {
  return db.one<{ id: string }>(
    `insert into alerts (id, agency_id, line_id, stop_id, severity, category, title, body,
                         starts_at, ends_at, status, issued_by, reach)
     values ($1, $2, $3, $4, $5, $6, $7, $8, now(), $9, 'active', $10, $11)
     returning id`,
    [
      input.id,
      input.agencyId,
      input.lineId,
      input.stopId,
      input.severity,
      input.category,
      input.title,
      input.body,
      input.endsAt,
      input.issuedBy,
      input.reach,
    ],
  );
}

export async function resolveInterventionAlert(db: Queryable, id: string): Promise<void> {
  await db.query(`delete from alerts where id = $1`, [id]);
}

export async function deleteDecision(db: Queryable, id: string): Promise<void> {
  await db.query(`delete from ai_decisions where id = $1`, [id]);
}

/** Map a ledger row to the payload shape the UI renders. */
export function toInterventionSummary(row: InterventionReadRow): AiInterventionSummary {
  const keys = Array.isArray(row.action_keys)
    ? (row.action_keys as AiActionKey[])
    : (JSON.parse(String(row.action_keys ?? '[]')) as AiActionKey[]);

  return {
    id: row.id,
    lineId: row.line_id,
    routeNumber: row.route_number,
    routeName: row.route_name,
    color: row.color,
    status: row.status,
    detectedAt: new Date(row.detected_at).toISOString(),
    appliedAt: row.applied_at ? new Date(row.applied_at).toISOString() : null,
    targetAt: new Date(row.target_at).toISOString(),
    minutesToCongestion: row.minutes_to_congestion,
    currentPct: Number(row.current_pct),
    predictedPct: Number(row.predicted_pct),
    projectedPct: Number(row.projected_pct),
    reliefPct: Number(row.relief_pct),
    confidencePct: Number(row.confidence_pct),
    actionKeys: keys,
    actionCount: Number(row.action_count),
    vehicleId: row.vehicle_id,
    vehicleCode: row.vehicle_code,
    alertId: row.alert_id,
    alertTitle: row.alert_title,
    appliedBy: row.applied_by,
    note: row.note,
    simulated: true,
  };
}

/** Level helpers shared by the service (bands live in `shared/crowd.ts`). */
export interface LineLiveLoad {
  line_id: string;
  stop_id: string;
  occupancy_ratio: number | string;
  level: CrowdLevel;
}

export async function getLineLiveLoad(
  db: Queryable,
  lineId: string,
): Promise<LineLiveLoad | null> {
  return db.one<LineLiveLoad>(
    `select line_id, stop_id, occupancy_ratio, level
       from v_line_crowding_now
      where line_id = $1
      order by occupancy_ratio desc
      limit 1`,
    [lineId],
  );
}
