import type { Queryable } from '../db/client';
import type { CrowdLevel, TransitMode } from '../../shared/types';

/**
 * Command-centre repository — the raw, database-side half of the operator
 * console. Every number the control room shows is aggregated here in SQL from
 * real rows (`crowd_observations`, `v_line_crowding_now`, `crowd_forecasts`,
 * `vehicles`, `alerts`, `line_stops`, `service_patterns`).
 *
 * DEMO / SIMULATED DATA: the rows themselves are generated by the demo seed.
 */

export interface CommandNetworkRow {
  active_routes: number;
  total_routes: number;
  total_vehicles: number;
  active_vehicles: number;
  maintenance_vehicles: number;
  idle_vehicles: number;
  passengers_onboard: number | null;
  network_capacity: number | null;
  avg_ratio: number | string | null;
  peak_ratio: number | string | null;
  monitored_stops: number;
  active_alerts: number;
  critical_alerts: number;
}

/** Network-wide counters + live load, in one round trip. */
export async function getCommandNetwork(db: Queryable): Promise<CommandNetworkRow> {
  const row = await db.one<CommandNetworkRow>(
    `select
       (select count(*)::int from lines where is_active)                        as active_routes,
       (select count(*)::int from lines)                                        as total_routes,
       (select count(*)::int from vehicles)                                     as total_vehicles,
       (select count(*)::int from vehicles where status = 'in_service')         as active_vehicles,
       (select count(*)::int from vehicles where status = 'maintenance')        as maintenance_vehicles,
       (select count(*)::int from vehicles where status = 'idle')               as idle_vehicles,
       (select coalesce(sum(onboard_count), 0)::int from v_line_crowding_now)   as passengers_onboard,
       (select coalesce(sum(capacity), 0)::int from v_line_crowding_now)        as network_capacity,
       (select round(avg(occupancy_ratio), 3) from v_line_crowding_now)         as avg_ratio,
       (select round(max(occupancy_ratio), 3) from v_line_crowding_now)         as peak_ratio,
       (select count(*)::int from v_line_crowding_now)                          as monitored_stops,
       (select count(*)::int from alerts where status = 'active')               as active_alerts,
       (select count(*)::int from alerts
         where status = 'active' and severity in ('major', 'critical'))         as critical_alerts`,
  );

  return (
    row ?? {
      active_routes: 0,
      total_routes: 0,
      total_vehicles: 0,
      active_vehicles: 0,
      maintenance_vehicles: 0,
      idle_vehicles: 0,
      passengers_onboard: 0,
      network_capacity: 0,
      avg_ratio: 0,
      peak_ratio: 0,
      monitored_stops: 0,
      active_alerts: 0,
      critical_alerts: 0,
    }
  );
}

export interface CommandLineRow {
  line_id: string;
  code: string;
  name: string;
  color: string;
  mode: TransitMode;
  capacity_per_vehicle: number;
  headway_minutes: number;
  avg_ratio: number | string | null;
  max_ratio: number | string | null;
  peak_24h_ratio: number | string | null;
  headcount: number | null;
  capacity: number | null;
  stops_monitored: number;
  worst_stop_id: string | null;
  worst_stop_name: string | null;
  vehicles_total: number;
  vehicles_in_service: number;
  adherence_pct: number | string | null;
  active_alerts: number;
  major_alerts: number;
  next_departure_at: string | Date | null;
  first_departure: string | null;
  last_departure: string | null;
  peak_hour: number | null;
}

/**
 * One row per active route: live load (worst and average stop), fleet state,
 * service pattern and the next departure from the route's origin.
 */
export async function listCommandLines(db: Queryable): Promise<CommandLineRow[]> {
  return db.query<CommandLineRow>(
    `with first_stop as (
       select distinct on (line_id) line_id, stop_id
       from line_stops order by line_id, seq
     )
     select
       l.id   as line_id,
       l.code,
       l.name,
       l.color,
       l.mode,
       l.capacity_per_vehicle,
       l.headway_minutes,
       live.avg_ratio,
       live.max_ratio,
       (select round(max(o.occupancy_ratio), 3) from crowd_observations o
         where o.line_id = l.id and o.observed_at > now() - interval '24 hours') as peak_24h_ratio,
       live.headcount,
       live.capacity,
       coalesce(live.stops_monitored, 0) as stops_monitored,
       live.worst_stop_id,
       live.worst_stop_name,
       (select count(*)::int from vehicles v where v.line_id = l.id)                         as vehicles_total,
       (select count(*)::int from vehicles v
         where v.line_id = l.id and v.status = 'in_service')                                 as vehicles_in_service,
       (select round(coalesce(avg(v.adherence_pct), 100), 1) from vehicles v
         where v.line_id = l.id and v.status = 'in_service')                                 as adherence_pct,
       (select count(*)::int from alerts a where a.line_id = l.id and a.status = 'active')    as active_alerts,
       (select count(*)::int from alerts a
         where a.line_id = l.id and a.status = 'active'
           and a.severity in ('major', 'critical'))                                          as major_alerts,
       dep.departure_at     as next_departure_at,
       pat.first_departure::text as first_departure,
       pat.last_departure::text  as last_departure,
       (select p.hour_of_day from v_operator_line_load p
         where p.line_id = l.id and p.day_type = 'weekday'
         order by p.avg_ratio desc limit 1)                                                  as peak_hour
     from lines l
     left join lateral (
       select
         round(avg(r.occupancy_ratio), 3) as avg_ratio,
         round(max(r.occupancy_ratio), 3) as max_ratio,
         coalesce(sum(r.onboard_count), 0)::int as headcount,
         coalesce(sum(r.capacity), 0)::int      as capacity,
         count(*)::int                          as stops_monitored,
         (array_agg(r.stop_id   order by r.occupancy_ratio desc, r.stop_id))[1] as worst_stop_id,
         (array_agg(r.stop_name order by r.occupancy_ratio desc, r.stop_id))[1] as worst_stop_name
       from v_line_crowding_now r
       where r.line_id = l.id
     ) live on true
     left join lateral (
       select d.departure_at
       from first_stop fs
       cross join lateral fn_next_departures(fs.stop_id, now(), 240) d
       where fs.line_id = l.id
       order by d.departure_at
       limit 1
     ) dep on true
     left join lateral (
       select sp.first_departure, sp.last_departure
       from service_patterns sp
       where sp.line_id = l.id and sp.direction = 0
       order by sp.service_day
       limit 1
     ) pat on true
     where l.is_active
     order by live.max_ratio desc nulls last, l.code`,
  );
}

export interface CommandStopRow {
  line_id: string;
  code: string;
  name: string;
  color: string;
  mode: TransitMode;
  seq: number;
  stop_id: string;
  stop_code: string;
  stop_name: string;
  lat: number | string;
  lng: number | string;
  is_interchange: boolean;
  daily_boardings: number;
  live_ratio: number | string | null;
  live_level: CrowdLevel | null;
  live_headcount: number | null;
  live_capacity: number | null;
  forecast_ratio: number | string | null;
  forecast_confidence: number | string | null;
  forecast_at: string | Date | null;
  peak_ratio: number | string | null;
}

/**
 * Route geometry with live *and* next-horizon load per stop — the data behind
 * the crowd heatmap. The nearest future `crowd_forecasts` row is joined per
 * stop, so the map can be flipped between measured and predicted crowding.
 */
export async function listCommandLineStops(db: Queryable): Promise<CommandStopRow[]> {
  return db.query<CommandStopRow>(
    `select
       l.id as line_id,
       l.code,
       l.name,
       l.color,
       l.mode,
       ls.seq,
       s.id   as stop_id,
       s.code as stop_code,
       s.name as stop_name,
       s.lat,
       s.lng,
       s.is_interchange,
       s.daily_boardings,
       r.occupancy_ratio as live_ratio,
       r.level           as live_level,
       r.onboard_count   as live_headcount,
       r.capacity        as live_capacity,
       f.predicted_ratio as forecast_ratio,
       f.confidence      as forecast_confidence,
       f.target_at       as forecast_at,
       (select round(max(o.occupancy_ratio), 3) from crowd_observations o
         where o.line_id = l.id and o.stop_id = s.id
           and o.observed_at > now() - interval '24 hours') as peak_ratio
     from lines l
     join line_stops ls on ls.line_id = l.id
     join stops s       on s.id = ls.stop_id
     left join v_line_crowding_now r
       on r.line_id = l.id and r.stop_id = s.id
     left join lateral (
       select cf.predicted_ratio, cf.confidence, cf.target_at
       from crowd_forecasts cf
       where cf.line_id = l.id and cf.stop_id = s.id and cf.target_at > now()
       order by cf.target_at asc
       limit 1
     ) f on true
     where l.is_active
     order by l.code, ls.seq`,
  );
}

export interface CommandTrendRow {
  bucket: string | Date;
  ratio: number | string;
  line_id?: string;
}

/** Hourly network average over the trailing window (measured occupancy). */
export async function listNetworkHistory(db: Queryable, hours = 24): Promise<CommandTrendRow[]> {
  return db.query<CommandTrendRow>(
    `select date_trunc('hour', observed_at) as bucket,
            round(avg(occupancy_ratio), 3) as ratio
       from crowd_observations
      where observed_at > now() - make_interval(hours => $1::int)
      group by 1
      order by 1`,
    [hours],
  );
}

/** Hourly network peak from the persisted model forecasts, looking forward. */
export async function listNetworkForecast(db: Queryable, hours = 6): Promise<CommandTrendRow[]> {
  return db.query<CommandTrendRow>(
    `select date_trunc('hour', target_at) as bucket,
            round(max(predicted_ratio), 3) as ratio
       from crowd_forecasts
      where target_at >= now()
        and target_at < now() + make_interval(hours => $1::int)
      group by 1
      order by 1`,
    [hours],
  );
}

/** Per-route hourly history + per-route forecast buckets for the analytics row. */
export async function listLineHistory(db: Queryable, hours = 24): Promise<(CommandTrendRow & { line_id: string })[]> {
  return db.query<CommandTrendRow & { line_id: string }>(
    `select line_id,
            date_trunc('hour', observed_at) as bucket,
            round(avg(occupancy_ratio), 3) as ratio
       from crowd_observations
      where observed_at > now() - make_interval(hours => $1::int)
      group by 1, 2
      order by 2`,
    [hours],
  );
}

export async function listLineForecast(db: Queryable, hours = 4): Promise<(CommandTrendRow & { line_id: string })[]> {
  return db.query<CommandTrendRow & { line_id: string }>(
    `select line_id,
            date_trunc('hour', target_at) as bucket,
            round(max(predicted_ratio), 3) as ratio
       from crowd_forecasts
      where target_at >= now()
        and target_at < now() + make_interval(hours => $1::int)
      group by 1, 2
      order by 2`,
    [hours],
  );
}

export interface CommandAlertRow {
  id: string;
  line_id: string | null;
  line_code: string | null;
  line_name: string | null;
  line_color: string | null;
  severity: 'info' | 'minor' | 'major' | 'critical';
  category: string;
  title: string;
  body: string;
  starts_at: string | Date;
  ends_at: string | Date | null;
  reach: number;
}

/** Active notices that are relevant to the control room right now. */
export async function listCommandNotices(db: Queryable, limit = 8): Promise<CommandAlertRow[]> {
  return db.query<CommandAlertRow>(
    `select a.id, a.line_id, l.code as line_code, l.name as line_name, l.color as line_color,
            a.severity, a.category, a.title, a.body, a.starts_at, a.ends_at, a.reach
       from alerts a
       left join lines l on l.id = a.line_id
      where a.status = 'active'
      order by case a.severity when 'critical' then 0 when 'major' then 1 when 'minor' then 2 else 3 end,
               a.starts_at desc
      limit $1`,
    [limit],
  );
}

/** Ratio of vehicles in service per line, used for the "spare capacity" advice. */
export async function getFleetAvailability(
  db: Queryable,
): Promise<{ idle: number; maintenance: number; inService: number }> {
  const row = await db.one<{ idle: number; maintenance: number; in_service: number }>(
    `select
       (select count(*)::int from vehicles where status = 'idle')        as idle,
       (select count(*)::int from vehicles where status = 'maintenance') as maintenance,
       (select count(*)::int from vehicles where status = 'in_service')  as in_service`,
  );
  return {
    idle: Number(row?.idle ?? 0),
    maintenance: Number(row?.maintenance ?? 0),
    inService: Number(row?.in_service ?? 0),
  };
}
